spring:
  profiles:
    active: dev   #définir le profil actif

---
spring:
  config:
    activate:
      on-profile: dev
greeting:
  message: "👩‍💻 Bonjour depuis le profil DEV !"

---
spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: "🚀 Bonjour depuis le profil PROD !"
